version: '3'

services:
  shop-file-main:
    build: .
    container_name: shop-file-main
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8008:8000

